// <auto-generated />
using FoldreView.Models.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FolderView.Models.Migrations
{
    [DbContext(typeof(FolderContext))]
    [Migration("20191027195206_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("FoldreView.Models.Database.Folder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Folders");

                    b.HasData(
                        new { Id = 1, Name = "Creating Digital Images" },
                        new { Id = 2, Name = "Resources" },
                        new { Id = 3, Name = "Evidence" },
                        new { Id = 4, Name = "Graphic Products" },
                        new { Id = 5, Name = "Primary Sources" },
                        new { Id = 6, Name = "Secondary Sourcess" },
                        new { Id = 7, Name = "Process" },
                        new { Id = 8, Name = "Final Procuct" }
                    );
                });

            modelBuilder.Entity("FoldreView.Models.Database.FolderTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AncestorId");

                    b.Property<int>("DescendantId");

                    b.HasKey("Id");

                    b.HasIndex("AncestorId");

                    b.HasIndex("DescendantId");

                    b.ToTable("FolderTree");

                    b.HasData(
                        new { Id = 1, AncestorId = 1, DescendantId = 2 },
                        new { Id = 2, AncestorId = 1, DescendantId = 3 },
                        new { Id = 3, AncestorId = 1, DescendantId = 4 },
                        new { Id = 4, AncestorId = 2, DescendantId = 5 },
                        new { Id = 5, AncestorId = 2, DescendantId = 6 },
                        new { Id = 6, AncestorId = 4, DescendantId = 7 },
                        new { Id = 7, AncestorId = 4, DescendantId = 8 }
                    );
                });

            modelBuilder.Entity("FoldreView.Models.Database.FolderTree", b =>
                {
                    b.HasOne("FoldreView.Models.Database.Folder", "AncestorFolder")
                        .WithMany("AncestorTree")
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FoldreView.Models.Database.Folder", "DescendantFolder")
                        .WithMany("DescendantTree")
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
